ios/ReviewViewController.m
This resolves issue https://github.com/davidsansome/tsurukame/issues/45.
Now setting `answerField.placeholder` to either `@"答え"` or `@"Your Response"`, as appropriate.
=> (#45) Adds “Your Response” / 「答え」hint text to review prompts.

ios/AnswerChecker.m
i sometimes hit the space bar by accident, inserting random spaces into the reading answer, this should strip out any space before doing the check.
this is assumes there is never any space required in any reading answers (not sure if that's the case)
=> ignore spaces in reading answers

README.md
The `data` folder probably doesn’t exist the first time you follow the instructions. In that case the subsequent command will fail:
```
panic: directory data does not exist
goroutine 1 [running]:
github.com/davidsansome/tsurukame/utils.Must(...)
/Users/play/go/src/github.com/davidsansome/tsurukame/utils/utils.go:9
main.main()
/Users/play/Desktop/tsurukame/cmd/scrape/main.go:49 +0x174
exit status 2
```
=> Adds `mkdir data` to README.md instructions

ios/AppDelegate.m
Right now, the only thing keeping Allicrab installed on my phone is the notifications when new reviews or lessons are available. This PR adds local notifications at the same time as the badge number updates to show how many reviews are available.
Closes #64.
=> Review notifications

ios/SettingsViewController.m, ios/SubjectDetailsView.m, ios/UserDefaults.h, ios/UserDefaults.m, ios/proto/Wanikani+Convenience.m
I recently started using WaniKani and Tsurukame. I noticed that there have been changes to the mnemonics for radicals over the years and old mnemonics are still shown in the app, possibly for existing users. While learning new radicals as a new user, I can't help but also look at the old mnemonics and I tend to get confused.
In this PR I am adding a new setting "Show Old Mnemonics" that is enabled by default which keeps the current behavior of the app. When disabled it will hide the old meanings both from the levels view as well as the detail view. I did not make them invalid as answers because it is only meant to be a visual change. It will also ensure that future updates to radical mnemonics won't disrupt current users.
Click this image for a [video](https://youtu.be/soIZ85Mu-CQ) …
=> Add a setting to hide old mnemonics from radicals.

ios/ReviewViewController.mm
This PR resolves #95 by allowing ReviewViewController to become the first responder itself. That way, after the `answerField` resigns first responder on line 644, the ReviewViewController can still respond to the return key and move on to the next question.
https://github.com/indirect/tsurukame/blob/74b9c80ab058a45bd0e6aa02ef6434ef810f0d60/ios/ReviewViewController.mm#L644
=> Advance on "return" after wrong answer

ios/Main.storyboard, ios/ReviewViewController.mm
For reasons I don't really understand, increasing the question label
font size inside `viewDidLoad` only makes the question appear bigger
during lesson quizzes, and does not make the question appear bigger
during reviews. I think it might be because of the setupContext block,
but I wasn't able to fix it by changing that.
Setting the font size to the correct size in `viewWillLayoutSubviews`
always seems to work, so I'm now doing that.
This patch increases the font size for both custom fonts and the system
font, in both lessons and reviews, both when tapping on the question
label and when not tapping on the question label.
=> Enlarge font in reviews also

ios/LessonsViewController.m
When viewing new lessons, the left and right arrow keys now page back and forth, including starting the quiz.
=> allow lesson navigation using keyboard arrows

overrides.txt
I filed a ticket with WK, but in the meantime this changes the invalid `<rd>` tag into a valid `<reading>` tag and makes the reading mnemonic readable in the app. For some reason the WK website just ignores the invalid start and end tags, but the data.bin instead ends up missing a big chunk of the text without this fix.
=> Fix reading mnemonic for 都合

ios/LessonsViewController.m, ios/SubjectDetailsView.h, ios/SubjectDetailsView.m, ios/SubjectDetailsViewController.h, ios/SubjectDetailsViewController.m, ios/Tables/TKMReadingModelItem.h, ios/Tables/TKMReadingModelItem.m
This integrates well with keyboard control for navigating lessons, making it possible to learn new subjects (including hearing their readings) without having to tap on the screen.
=> Add space as keyboard shortcut to play reading

ios/LessonOrderViewController.h, ios/LessonOrderViewController.m, ios/Main.storyboard, ios/ReviewItem.h, ios/ReviewItem.m, ios/SettingsViewController.m, ios/Tsurukame.xcodeproj/project.pbxproj, ios/UserDefaults.h, ios/UserDefaults.m
When leveling up, a lot of radicals, kanji and vocabulary become available at the same time. I usually tend to study ~5 new kanji per day which means that it often happens that I'll only get to study vocabulary once I am pretty close to leveling up again. I prefer to work myself through both kanji and vocabulary at the same time to reduce the load of new words towards the end of a level. Currently I use the wanikani website with a custom userscript but I'd prefer to use Tsurukame exclusively because of the much better user experience.
This PR adds two new options to customize which items are taught first in the lessons screen:
* Prioritize current level (default: disabled): When enabling this option, items from the current (highest) level will be shown before any lower levels.
* Sort by …
=> Add ability to customize lessons

ios/TKMAudio.m
This addresses #118.
See the [documentation on this feature](https://developer.apple.com/documentation/avfoundation/avaudiosessioncategoryoptions/avaudiosessioncategoryoptioninterruptspokenaudioandmixwithothers?language=objc).
Apologies in advance for any errors, my iOS development experience is quite limited.
=> Appropriately duck/pause background audio

ios/SubjectCatalogueViewController.m, ios/UserDefaults.h, ios/UserDefaults.m
This creates a user default that isn't actually used in the settings view. Instead it is controlled and read directly by the show answers toggle in the SubjectCatalogueViewController. I found myself not really wanting to see the answers and was wanting a way to have it be off when I enter the view!
I'm not sure if this breaks any kind of paradigm since I don't think there are any existing settings that persist outside of the settings view, so this might throw someone off. If it is preferred to be maintained from there, I can move it there, where it could be in a new section called "Catalogue" and named "Show answers by default" or something.
Let me know what you think!
=> Persist SubjectCatalogueVC's show answers toggle

ios/Style.m
This is a fix for #135, and switches to the font weights that are included with iOS according to both Apple's System Fonts page and real-life listing of available fonts as detailed in that issue's comments.
=> Use font weights that iOS has

ios/Client.m, ios/Main.storyboard, ios/MainViewController.m, ios/SubjectsRemainingViewController.h, ios/SubjectsRemainingViewController.m, ios/Tables/TKMSubjectModelItem.h, ios/Tables/TKMSubjectModelItem.m, ios/Tsurukame.xcodeproj/project.pbxproj
This is the screen I've always wanted in Tsurukame, and I think means that I won't need to keep AlliCrab installed anymore (😅). The "Show remaining" screen shows the radicals and kanji that have not yet reached guru status on the current level, along with the next times each item will be reviewable and could potentially reach guru. Here's what it looks like:
=> Add "Show remaining" screen showing level progress

ios/Tables/TKMListSeparatorItem.h, ios/Tables/TKMListSeparatorItem.m, ios/Tables/TKMListSeparatorItem.xib, ios/Tables/TKMTableModel.m
I noticed that you could tap on the separators, and they would stay selected and highlighted forever. This stops that by keeping them from being selectable.
=> stop allowing ListSeparatorCell to be selected

ios/proto/Wanikani+Convenience.m
Here's where we allow srsStage to go all the way back to zero if the
item is missed enough times:
https://github.com/davidsansome/tsurukame/blob/ebafb39423fed00ba2414ddacfbe83c5e095393d/ios/LocalCachingClient.mm#L671
We shouldn't treat them as locked just because their srsStage has
dropped back to zero.
fixes #148
=> Review items can reach srsStage zero if missed

ios/Tables/TKMSubjectModelItem.m
After using the app, the "remaining time" that makes the most sense to me for items that are "available in lessons" is the amount of time it would take if you were to do the lesson immediately and then get every following review correct. This commit implements that.
=> Give Available Lessons a remaining time that makes sense

ios/ReviewViewController.mm, ios/Style.m
This makes it so the `tab` key toggles the displayed font (like long
pressing does) during reviews. This addresses #117.
There's a little bit of weirdness around font names in iOS it seems, so there may be a simpler way of doing this.
=> Add keyboard shortcut toggling font randomization

ios/ReviewViewController.mm
It's easy to accidentally type a single letter by itself after missing a review, and the cheat actions have no undo. By making these shortcuts command key shortcuts, it's much harder to accidentally trigger them.
Fixes #166, I think.
=> Make keyboard cheats use the command key

ios/ReviewViewController.swift
This is the only patch that seemed really needed to make reviews on macOS work. Without this patch, you have to click the mouse to focus on the text entry box after each animation. With this patch, you can type answers one after another, like on an iPhone or iPad.
=> Allow reviews without clicking on macOS

ios/MainViewController.m
The main screen keyboard shortcuts for lessons and reviews would wrongly try to trigger even if there were no lessons or reviews, and could get the app into a stuck state.
This also adds a convenience shortcut of "push return to keep studying", which will work as long as there are reviews or lessons remaining.
=> Study shortcut improvements

ios/SubjectDetailsView.swift
Fixes #206 - should be "Kanji" not "Kanhi".
=> Fixed typo (#206)

ios/CurrentLevelChartItem.swift, ios/LessonsViewController.m, ios/LevelTimeRemainingItem.swift, ios/ReviewViewController.swift, ios/SRSStageCategoryItem.swift, ios/Style.swift, ios/SubjectDetailsView.swift, ios/Tables/TKMAttributedModelItem.m, ios/Tables/TKMMarkupModelItem.m, ios/UpcomingReviewsChartItem.swift
This fixes the main (and easy) bits from #216.
In dark mode:
In light mode:
=> Dark mode fixes

ios/CurrentLevelChartItem.swift, ios/proto/Wanikani+Convenience.h, ios/proto/Wanikani+Convenience.m
To match with other resources, fix #224, and to allow former "Novice" items to be in the SRS stages list, this commit proposes to rename SRS stages 1-4 back to Apprentice 1-4, like on WK.
=> Renamed Novice to Apprentice I (Fixes #224)

ios/Settings.h, ios/Settings.m, ios/SettingsViewController.m, ios/SubjectDetailsView.swift
Implements https://github.com/davidsansome/tsurukame/issues/230
* Unless requested, I opted not to make separate sections for each type of reading as @sciencemanx brought up a good point about it potentially taking up too much room before getting to the "meat" of the entry/subject.
* Primary readings are always first. If more that one reading exists, the primary one(s) will be in bold.
* Kanji/Vocabulary with multiple readings
* Kanji/Vocabulary with one reading (functions the same as today)
* No changes in radicals
* No changes
=> Add Option to Show All Readings

ios/LevelTimeRemainingItem.swift
To attempt to fix #222, this code attempts to check the last radical guru time if a kanji is still locked.
**EDIT:** Thanks for helping with CircleCI! I was trying to work on this issue on vacation, so I couldn't use my computer to test the builds.
=> Check how long until radical guru (Fixes #222)

README.md
Now that the JSON API is no longer used, the README needs to be updated to address this.
=> Update README with recent changes

ios/MainViewController.swift, ios/ReviewItem.h, ios/ReviewItem.m
This further addresses the problem where the 'hills' radical was always being shown in lessons for some users.
See #324 and #338.
=> Stop lessons from higher levels appearing

ios/ReviewViewController.swift
This treats the case where a SubjectDetailsView can lose its keyboard focus during navigation events in reviews, and the expected keyboard commands do not work.
Fixes #369.
=> Set the subject details view to be first responder when needed

ios/ReviewViewController.swift
Fix #321. If the setting is off, we should never reveal it automatically, and if it's on, we should always reveal automatically.
=> Change auto-reveal condition (Fix #321)

ios/ReviewViewController.swift, ios/SubjectDetailsView.swift, ios/SubjectDetailsViewController.m
This PR fixes #49 by hiding parts of an answer during reviews that haven't been attempted yet, and the last answered review pop-up will now be shown for half-answered reviews due to this being fixed. _(Side note: This may not be an ideal solution since there is no way to see the correct answer if you want to. You may want to explore the possibility of re-introducing the blurring.)_
This PR also partially addresses #257 by adding the stats section, but it doesn't add a resurrect button since the API [hasn't exposed an endpoint for that yet.](https://community.wanikani.com/t/official-announcement-on-upcoming-api-version-2-breaking-changes-addition-of-new-endpoint-spacedrepetitionsystems/44423/73)
=> Hide summary & add stats section

ios/Settings.swift
Based on #388, this PR should theoretically prevent loss of settings from before the Swift conversion.
To test this after merging, set settings that were not previously encoded with NSKeyedArchiver (such as font size, review order, etc.) on TestFlight build 309, then upgrade to a not yet extant TestFlight build containing this commit.
=> Add safeguard to prevent setting wipe from old format (Fixes #388)

ios/InterfaceStyleViewController.swift, ios/ReviewViewController.swift, ios/Settings.swift
This PR fixes #398 by reverting the change in storage of enum values, so that the interface style and review order preferences will not be wiped, and encoding any settings which have not been encoded.
=> Correct not encoded settings (Fixes #398)

ios/AnswerChecker.swift
This commit enables a single, trailing 'n' entry to be converted to 'ん' on answer submission, to be like other kana input sources, where it otherwise requires entering 'nn' to be complete.
Note that hardware keyboard input on iOS requires two enter presses to complete 'ん' from 'n' with this behavior being the same for other Japanese keyboards.
=> Allow trailing n-kana completion in Gboard Godan layout

ios/ReviewViewController.swift, ios/SubjectDetailsViewController.m
Fixes #372 by adding key commands for the previous subject button, and to return back to the review view controller.
These new commands are "p" and the left arrow, respectively.
=> Add two additional keyboard commands (Fixes #372)

ios/ReviewViewController.swift
Key command 'p' for previous subject interferes with hardware keyboard answer input. This change adds a command-key modifier to prevent that.
=>  Prevent input interference with a modifier for previous subject

ios/Resources/Main.storyboard
Quick fix for issue #313. Made number of lines 2 instead of one. Maybe it should be 0? 
I used Xcode 12.0.1 so that might have caused the extra storyboard changes
Screenshots on 11 pro with 125% font size
| Before        | After           |
| ----------- |------------|
| ![Simulator Screen Shot - iPhone 11 Pro - 2020-10-03 at 17 25 17](https://user-images.githubusercontent.com/15106299/94996691-0ca45500-059e-11eb-928b-c90ab14043e5.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-10-03 at 17 24 45](https://user-images.githubusercontent.com/15106299/94996697-129a3600-059e-11eb-85e9-2d9def7698e6.png) |
=> Make review label number of lines 2

ios/Extensions/ProtobufExtensions.swift
Fixes #434 by correcting `minimumTimeUntilGuru(itemLevel:)`
=> Fallthrough in minimum time to guru to fix wonko review times

ios/Settings.swift, ios/SettingsViewController.swift, ios/SubjectDetailsView.swift
Fixes #448 by adding a new option to hide the stats section. The stats section will be on by default, to keep it the same way it is right now.
This also fixes #445 by reversing the default for `useKatakanaForOnyomi` accidentally changed in #382
=> Add option to hide stats section

ios/Settings.swift
The original lines in `setArchiveData`, from the original Swift conversion, inadvertently stores settings in a format that `getArchiveData` can't read for iOS 10 users. This PR corrects this issue.
=> Fix Settings implementation of setArchiveData for iOS 10

ios/ReviewViewController.swift, ios/SubjectDetailsView.swift, utils/set-team-product.sh
Due to bugs, the exact match setting does nothing, the script to change bundle identifers incorrectly matches the doctypes in the complication property lists, and if you review and get the reading wrong but haven't answered the meaning, or vice versa, there's no way to show the meaning and its explanation.
By fixing these bugs, this PR will resolve #86, resolve #172, and resolve #463.
=> Fix useless exact match & unshowable subject details

ios/CurrentLevelReviewTimeItem.swift
To follow with the original reasoning in #254, this PR will exclude assignments from being included that have already passed, since they are no longer relevant for level-up purposes.
=> Ignore passed items in current level

ios/SettingsViewController.swift
The bug fixes in #478 seem to have accidentally forgotten to add the exact match setting to SettingsViewController. This PR corrects that.
=> Add toggle for newly fixed exact match setting so users can set it

ios/AppDelegate.swift
Implements the first point of #362 by including how many of the reviews newly available are new reviews in the notification.
=> Include number of newly available reviews in the notification

ios/LevelTimeRemainingItem.swift, ios/ReviewViewController.swift, ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
To prepare for other spaced repetition systems in WaniKani, this PR requires a TKMSubject in order to calculate duration, as opposed to simply an item level.
=> Require TKMSubject for duration instead of item level

ios/ReviewViewController.swift, ios/SettingsViewController.swift
Wider testing revealed that Anki mode conflicted with the reveal answer immediately and skipping reviews settings.
This PR fixes that by hiding all buttons that are present in non-Anki mode reviews, and building in a submit functionality when pressing the question label.
=> Fix Anki mode conflicts with reveal immediately & skipping reviews

ios/LocalCachingClient.swift
In the event `availableSubjects.reviewComposition` is an empty array, using a range to create an ArraySlice will fail. Using `dropFirst()` to create it removes this risk, since it falls back on an empty array if the array is too small.
=> Fix crash on empty array by using dropFirst() instead of [1...]

ios/ReviewViewController.swift, ios/SettingsViewController.swift
Fixes #494 by using the existing reveal answer automatically setting to toggle the instant revealing of the Anki mode mark answer pop-up.
Since this setting is already a quick setting in the menu, it can be toggled without leaving reviews.
=> Use reveal answer automatically to reveal Anki mark answer pop-up

ios/SubjectsRemainingViewController.swift
Fixes #443 by adjusting the loop condition to properly loop through all assignments.
=> Fix items showing up in wrong SRS section (Fixes #443)

ios/LocalCachingClient.swift, ios/MainViewController.swift, ios/Resources/Main.storyboard, ios/Settings.swift, ios/SettingsViewController.swift, ios/Tsurukame.xcodeproj/project.pbxproj, ios/UpcomingReviewsChartItem.swift, ios/UpcomingReviewsViewController.swift
Implements the first half of #112 by adding the list, and fixes #274 by breaking down the review count in the list by SRS (which can be toggled to item type)
The list is opened by tapping the graph, as if for more details.
=> Upcoming reviews list view (Fixes #274)

ios/UpcomingReviewsViewController.swift
There's no guarantee that the dictionaries passed will actually be sorted in a readable order. This PR corrects that issue.
=> Properly sort list view dictionaries before outputting them

ios/LevelTimeRemainingItem.swift
Fix a bug accidentally introduced in #485 that prevents locked or lesson stage kanji from contributing to it, and only treat locked kanji as locked, instead of just those without reviews available (e.g. lesson stage, or burned).
=> Allow locked kanji to contribute to LevelTimeRemainingItem, and correct definition of locked

ios/ReviewViewController.swift
In trying to implement #495, I got overconfident and forgot to test. As it turns out, once the answer is marked incorrect, the subject details view is always shown, so the value of what it was before needs to be saved.
=> Fix bug in #495

ios/ReviewViewController.swift
These commands shouldn't be restricted to just macOS. iPad users might find them beneficial!
=> Remove macOS restriction on key commands

ios/FontLoader.swift, ios/LocalCachingClient.swift, ios/UpcomingReviewsViewController.swift
This PR makes a few manual formatting adjustments, and then ran SwiftFormat.
Please note the space inserted on line 35 of `LocalCachingClient.swift`. If you think it looks cleaner, you don't need to do anything. However, if you don't like it, you'll need to add the SwiftFormat rule `--operatorfunc no-space`
=> Format recently inserted lines

ios/SubjectDetailsView.swift, ios/WaniKaniAPI/Sources/WaniKaniAPI/APIClient.swift, ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift, ios/WaniKaniAPI/Sources/WaniKaniAPI/wanikani_api.pb.swift, proto/wanikani_api.proto
This PR allows users to see the date they have burned an item in the stats section.
For future reference, in order for the burned date to be cached into the client the first time, users would have to perform a full refresh (since caches created prior, of course, wouldn't contain the burned at date).
=> Add burned field to stats section

ios/Tsurukame.xcodeproj/project.pbxproj
This PR renames the tests bundle identifier to be consistent with the `com.davidsansome.wanikani` used for other bundle identifiers. It seems to be a relic of the original name of the app.
P.S. When you review this, could you also review #524? It's also really small.
=> Rename tests bundle identifier

ios/Tables/TableModel.swift
There's probably a better way to do this, I just don't know it. Somehow the UILabel for the section header has decided that it has zero lines, and so on iPad and Mac the automatic height is getting collapsed down to nothing.
Before this change:
After this change:
Fixes #558.
=> Fix main screen section header height on iPad and Mac

ios/ReviewSummaryViewController.swift
Adds a keyboard shortcut 
(Return / ↩) to dismiss the review summary screen and return to the main screen. This makes it possible to review and then move on to lessons (or more reviews, if they have come up) from the keyboard.
Fixes #559.
=> Dismiss review session summary with keyboard

ios/ReviewViewController.swift
Keeps keyboard focus on the input field after pressing "return" at times when focus was previously lost, including when the input is empty, or when the answer is wrong. With this patch applied, it becomes possible to miss a review, read the subject details, and still be able to press return again to continue. It also preserves focus in the cases where the answer was neither right nor wrong and produced a screen shake.
Tested on iPhone, iPad, macOS (Designed for iPad), and macOS (Catalyst). Seems to work!
Fixes #560
=> Keep keyboard focus, even after wrong answers

ios/Resources/Main.storyboard, ios/Tables/TableModel.swift
thanks to a friend at apple, it was pointed out to me that the storyboard xib had hardcoded section heights, apparently originally due to a long-ago bug in xcode. removing the incorrect hardcoded heights from the xib means my weird hack-around isn't needed anymore! phew.
=> fix section header clipping the right way

ios/ReviewViewController.swift, ios/SubjectDetailsView.swift, ios/SubjectDetailsViewController.swift
after missing a reading, WaniKani shows the correct reading, but hides the meaning and the mnemonics. there is [a keyboard shortcut][1] to show the hidden information: spacebar.
This can (sometimes) conflict with an existing keyboard shortcut to play the audio reading for a vocabulary word. I have tried to preserve that behavior everywhere possible, and only take over the shortcut when there is hidden information to show.
This commit makes Tsurukame match the WaniKani website shortcuts "f" (to show details after an incorrect answer), "spacebar" (to show the hidden full information while viewing details), and "j" (to play the audio recording of a vocabulary word while viewing details).
[1]: https://knowledge.wanikani.com/wanikani/keyboard-shortcuts/
=> match WaniKani keyboard shortcuts in details pane

ios/LevelTimeRemainingItem.swift, ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
When a Wanikani user resets to a lower level, the level they were on when they reset never gets a `completedAt`, it gets `abandonedAt` instead. That means we have been including the entire time from the moment each abandoned/reset level was started until the present moment in the average calculation—for me personally, that meant the estimated level times were around 90 days. Excluding level time records that have an abandonedAt present fixes the estimation. While reviewing the calculation, I noticed that we were sometimes including zeroes in the list of level times, so I added a check to remove those.
Before: Estimated level time 90d
After: Estimated level time 10d
Since I have never taken 90 days to complete a level, and usually take about 10 days, it seems like that fixed it.
=> Account for resets when estimating level time

ios/AppDelegate.swift, ios/AppStoreScreenshots/Screenshotter.swift, ios/LoginViewController.swift, ios/MainViewController.swift, ios/Resources/Main.storyboard
Adds alternative login method using API token rather than username/password credentials. User has the option to use one login method or the other, so this should not turn people away from using the app at all.
I did have to tweak the layout of the main login screen to accommodate the extra height. Also tweaked the shadow to make it more readable since the main Sign In text moved into a lighter background, but that's arguably opinionated and can be easily removed. See below screenshot.
Downside: User email address cannot be obtained via the API, thus making the gravatar fetch not work. In theory, we could add a setting that would allow users to override their email address used for Gravatar pulling. Is this a good option, or is there another way to grab the user's email address without web …
=> Allow API token login

ios/LocalCachingClient.swift, ios/MainViewController.swift, ios/Settings.swift, ios/SubjectDetailsSettingsViewController.swift, ios/SubjectsRemainingViewController.swift
One downside to passing kanji is that you level up before you finish vocabulary. For those of us who are ordering things such that we finish vocab before we start the next level's radicals/kanji, it would be useful to see a graph of our current progress.
This PR adds a setting to enable that. If active, it will check to see if the user's previous level (the one where they have vocabulary) is done or not. If it is not done, a second graph is shown on the home screen with the title `Current Level (#)`, and then the user's _actual_ current level graph is titled with `Next Level`. If the setting is on and the user has finished the prior level, it will only show the current level's graph.
I also renamed `This Level` to `Current Level` if the setting is off (or does not apply); that is more of …
=> Add option for viewing current level graph before finishing vocab

ios/LocalCachingClient.swift, ios/ReviewItem.swift
Due to [WaniKani's recent change](https://community.wanikani.com/t/higher-level-items-in-review-queue/57004), the feature introduced in #269 is now preventing Tsurukame users from performing some of their reviews.
This reverts commit d271ff95641ab63205c7901c1e0086ceaaaf0d56 and fixes #591.
=> Revert #269 (Fixes #591)

ios/TKMKanaInput.m
I have no idea why this is now breaking sometimes on Mac, in both Catalyst and iPad modes. This fixes the text suddenly becoming left-aligned after every replacement of kana, but it does not fix the text suddenly jumping to the left if you click inside the text field.
I wasn't able to figure out how to force the text back to the center when you click on the text field. My attempts to intercept `becomeFirstResponder` and `textFieldDidBeginEditing` didn't work, but I don't know if it's because that isn't the problem or if it's because I am not good enough at UIKit. 😅
**Before**
https://user-images.githubusercontent.com/78/221395112-803e97b5-bf66-4a14-9ed5-4cef7574a448.mp4
**After**
https://user-images.githubusercontent.com/78/221395123-38077bba-1eed-400c-a971-7f20e594a8df.mp4
=> Force text back to center after kana replacement

ios/UpcomingReviewsChartItem.swift
Fixes issue #614 Upcoming reviews displayed as decimals
Before:
After:
=> Display upcoming review count without decimals

ios/WaniKaniAPI/Sources/WaniKaniAPI/HTTPURLResponse+valueForHeaderField.swift
Fix #619 with a one-line fix to a polyfill for iOS 12.
I have tested this PR in the iOS 12 simulator and confirmed it fixes the crash.
=> Fix iOS 12 crash

ios/CurrentLevelReviewTimeItem.swift, ios/ReviewSettingsViewController.swift, ios/Settings.swift
The current default behavior of not showing minutes means that as a user I have to add the minutes on in my head. This setting removes that mental load if the user so desires.
=> Add ability to show minutes for upcoming level up review

ios/SubjectDetailsView.swift
Content sentences are too small for my aging eyesight. This pull request scales the font size depending on the accessibility settings under:
Display & Text Size -> Larger Text 
Fixes #624
=> Have the font used for context sentences change size depending on accessibility options.

ios/AppDelegate.swift, ios/AppSettingsViewController.swift, ios/Settings.swift
@davidsansome Implemented a new 'Sounds' toggle within the application's notification settings. When toggled, this feature will control the audible alerts for incoming notifications, providing users with a more customizable experience. This change ensures that our app aligns with common user expectations for notification management, enhancing overall usability.
Issue: #650
=> Add 'Sounds' toggle for Notification Settings

ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
Minor error in projection calculation if an item exceeds guru and then falls below it
=> Gurued item that falls to apprentice is passed for level-up

ios/LocalCachingClient.swift, ios/MainViewController.swift, ios/Resources/Main.storyboard, ios/ReviewContainerViewController.swift, ios/ReviewItem.swift, ios/ReviewSession.swift, ios/ReviewViewController.swift
This PR adds three new practice features to the app: review recent mistakes, review recent lessons, and review burned items.
Works like the website. You can review mistakes from the last 24 hours. Readings and meanings are grouped like on the website. This PR does not add the "redo lessons" feature like the website has.
Because [the API does not currently let you get review history](https://community.wanikani.com/t/api-changes-get-all-reviews/61617), however, this is only a local cache of recent mistakes. In theory, if/when that API comes back, this functionality will need to be updated/enhanced.
UI to get here is on the main screen and in the "Upcoming Reviews" section.
Works like the website. You can review your recent lessons, review-style. Readings and meanings are grouped like on the …
=> Add extra practice methods: recent mistakes, recent lessons, burned items

ios/LocalCachingClient.swift
My last PR, #674, had a small issue where recent mistakes were not sticking around in the database after an online assignment fetch due to `subject_progress` being wiped via a `REPLACE INTO` statement in `LocalCachingClient.fetchAssignments`. Instead of using `REPLACE INTO`, performs an `UPDATE` followed by an `INSERT` if the `UPDATE` did nothing.
Also fixes an issue I found where logging out of one account into another account without restarting the app didn't clear cached numbers in `LocalCachingClient`. Fixes this by invalidating items in `LocalCachingClient.clearAllData`. Also noticed that a force refresh would not clear the recent lesson count cached number from the web, so I also invalidated that on `sync`.
Closes #676
=> Fixes recent mistakes not sticking around after sync, cached #'s not being invalidated after logout/login

ios/AppSettingsViewController.swift, ios/MainViewController.swift, ios/Settings.swift, ios/Tables/EditableTextModelItem.swift
Allows the user to put in a custom Gravatar email address. Useful for API key users, as there is currently no other way to specify the email address used for Gravatar, and API key users don't get their email address pulled from the API. So unless a way to add a Gravatar email address is added, there is no way for API key users to get out of using the default avatar.
Also updates `EditableTextModelItem` to allow for custom auto capitalization rules as well so that the email isn't auto-capitalized.
=> Feature: Custom Gravatar email address

ios/MainViewController.swift
Thanks for merging that last PR. After another test via TestFlight, everything works well. So, whether it was a weird caching fluke before (which we can now hopefully avoid that with a manual cache clear in the future), or if the SHA256 just works better on the Gravatar end for whatever reason, I'd call the problem "solved" and #635 can be closed as fixed. Left in the log statement for any future debugging that comes up.
This PR allows for the Gravatar override to also work for username/password logins instead of just API logins. Tested on simulator and device and it seems to work as expected. Hopefully this is the final Gravatar-related PR from me for a while.
(Apologies for all the PR's and activity last few days. Hope you don't mind. I do have one more minor bug fix for the "Recent …
=> Allow override of Gravatar with email/pass login

ios/LoginViewController.swift, ios/SubjectDetailsView.swift
* Actually show an error message to the user on API login failure instead of just "Invalid API token!"
* Force login view to be in light mode at all times. This one is subjective, I'll admit, but I'd like to argue that dark mode doesn't look good on the login screen, and I'm not sure making an entirely new UI for login for dark mode is worth the effort. See screenshots below. At the very least, this will make it look better for now until someone with more UI skills than I can improve it in dark mode.
* Fixes #578 by setting subject details background color to `UIColor.clear` rather than `TKMStyle.Color.cellBackground`. Why this is needed is unknown to me right now as the same color comes out of `TKMStyle.Color.cellBackground` on iOS vs macOS yet macOS needs the tweak. It doesn't hurt …
=> A few small UI fixes

ios/LocalCachingClient.swift
Should only set this field for reviews, not lessons, based on comparison to Recent Mistakes feature on WK website. Or, you know, just don't make mistakes while doing your lessons. 😉
=> Fix lesson mistakes setting last_mistake_time

ios/ReviewItem.swift
If an item is a recent mistake and is in the recent mistakes section BUT also was in the currently available review queue, it wasn't showing up in your recent mistakes queue. (The # on the main menu was correct and accurate, but when you tapped to do your recent mistake reviews, the items in the recent mistakes list that you were actually going to practice didn't match [there was a smaller number of things to practice]). 
Fixes the bug so what is on the main menu matches what you actually get to review/practice for recent mistakes — even if it is a recent mistake and is in the review queue, it should still be in the recent mistakes queue until 24 hrs have elapsed or until you get it right in a review.
Have verified that this behavior matches the website.
=> Fixes: Recent mistakes that were in review queue did not show up in recent mistakes review

ios/LessonPickerViewController.swift, ios/MainViewController.swift, ios/Resources/Main.storyboard, ios/Tables/SubjectModelItem.swift, ios/Tsurukame.xcodeproj/project.pbxproj
Allows user to choose which lessons they want to do next. Based on feature from WK website. Lesson picker only shows up if user has available lessons and hasn't hit their apprentice count. Separates lessons by level and lesson type (radical vs kanji vs vocab).
Made some minor tweaks to the `SubjectModelItem` class to support using those types of cells with checkmarks. Added a new `LessonPickerViewController`. Other than that, pretty standard minor changes (new segues, main menu table cell item, etc.).
Note: Does not currently perform checks to see if user has selected more lessons to do than (current apprentice count + number of lessons selected to do).
=> Feature: Add lesson picker

ios/ReviewViewController.swift
Fixes #706 
Related PR: #186  
[`becomeFirstResponder`](https://github.com/davidsansome/tsurukame/blob/ac4ed7f2261f772403d4b96bc7f8d18738e2744b/ios/ReviewViewController.swift#L769) was added in https://github.com/davidsansome/tsurukame/pull/186 to `ReviewViewController.animationDidStop` as a workaround specifically for macOS (starting at 10.15). At that time, the `answerTextField` would lose focus after each answer.
With current macOS (14.4), `answerTextField` no longer loses focus, but having the additional `becomeFirstResponder` triggered on `animationDidStop` causes the existing contents of `answerTextField` to be selected.
In my testing, the behavior of iOS on iPhone is not affected by this change either way.
=> Fix macOS issue where text input gets highlighted during reviews

ios/LessonPickerViewController.swift, ios/Resources/Main.storyboard
Finally figured out the difference between this and the `UpcomingReviewsViewController`: some properties on the table view sizing. Lesson picker now looks correct:
The removal of the `model.addSection()` in the lesson picker is not necessary for the fix; it just makes the UI look a little nicer.
Fixes #707
=> Bugfix: Fix lesson picker section text bleeding into nav bar

ios/SubjectsByCategoryViewController.swift
Very small change. Adds swipe-to-go-back capability to the Apprentice, Guru, Master, Enlightened, and Burned views via the SubjectsByCategoryViewController. This way it is in line with the "Show remaining" view (SubjectsRemainingViewController).
=> Adds swipe-to-go-back capability to the Apprentice, Guru, etc. categories.

ios/MainViewController.swift
user.currentLevel is capped at maxLevelGrantedBySubscription which causes #719 due to an implementation oversight
Fixes #719
=> Fix bug in main VC if level exceeds max granted by subscription

ios/ReviewViewController.swift
Maybe related: #724 (haven't replicated that one yet w/lack of testing; this is a bugfix I found by eye)
Should fix an issue where anki mode users, when practicing, updated things on the db/reviews instead of just moving considering it practice.
=> When in anki mode, pass `isPracticeSession` var

ios/ReviewSettingsViewController.swift
This is to address issue #745
adds extended description to the "review batch size" property to attempt to clear up confusion about what the setting actually does
the description I wrote is:
> The \(name) setting is ONLY used when "back-to-back" reviews are disabled.
>
> When "back-to-back" reviews are disabled, you might be asked to review the meaning of an item and then later after reviewing some other items, be asked to review the reading of that item.
> The \(name) setting controls the maximum number of different review items you can encounter between reviewing the reading and meaning for a given item."
=> docs(settings):  add extended description for "Review Batch Size"

ios/Audio.swift
I noticed an issue of momentary UI/interactivity stutters happening at the end of vocabulary audio playback. The stuttering would cause dropped keystrokes on the on-screen keyboard, or incorrect words to be input when using the swipe keyboard.
To reproduce the stutter, have another app on the device currently using an audio session, and then do some reviews and make sure to try typing around the time the audio playback finishes. I noticed the stutter when on a voice call concurrently while doing reviews, but it may also happen with other audio session types.
I tracked this issue down to the `setActive(false, ...)` of the audio session which happens on the main thread, and I imagine it has to do with the `.notifyOthersOnDeactivation` option letting another app block the main thread.
Either …
=> Deactivate audio session off main thread

ios/ReviewSettingsViewController.swift
This is for #745 
Once this is merged in, it should be much more obvious that the "batch size" submenu settings controls something related to non-back-to-back reviews.
- the "back-to-back order" submenu is hidden (existing behavior)
- the "batch size" submenu is visible (existing behavior) 
- the "back-to-back order" submenu is visible (existing behavior)
- the "batch size" submenu is hidden (**new behavior**)
=> feat(settings): conditionally hide "batch size"

ios/ReviewSettingsViewController.swift
closes #745 
renames the 'review batch size' property to reflect the actual behavior that it controls so that it's more obvious to users what they're actually changing when they tweak this setting
I landed on `Reviews Between Meaning & Reading` which I feel is extremely descriptive, yet concise and clear. I don't see how you could misunderstand the behavior of this property now.
=> refactor(settings): rename 'batch size' property to be more descriptive

ios/Tables/AttributedModelItem.swift, ios/Tables/ContextSentenceModelItem.swift
Closes #718
Closes #755 
It seems as though something is different in the way text is drawn in `ContextSentenceModelItem` and `AttributedModeltem` text measurement. Starting with iOS 16, `UITextView` changed its behavior for text layout. Reverting that change (to TextKit 1 layout) causes the Japanese text to draw the same for edge cases, but then the drawing in `ContextSentenceModelItem` is different.
To make it draw the same, grab the attributed string from the NSTextView and draw that instead. (The difference between the two attributed strings seems to be the font, interestingly enough, unless there is another attribute that I did not notice - I just checked via a simple print(), which may have skipped something).
So, said another way: The drawing in `ContextSentenceModelItem` draws …
=> Fix text drawing for context sentence blurring

ios/MainWaniKaniTabViewController.swift, ios/SubjectDetailsSettingsViewController.swift
The header names when showing your prior level graph have caused some confusion (see #622). This PR attempts to address those concerns by:
* Changing "Current Level (#)" (which is actually the prior level) to "Prior level being completed (#)"
* Changing "Next Level (#)" to the more intuitive "Current Level (#)", which will match the "Current Level" number everywhere else, including WaniKani's website
* Adjusting the settings text accordingly for clarity
**This is a text only change. Feedback and improvements to wording very welcome, but wanting to clean this up a bit.**
=> Tweak header names for current/next level

ios/MainWaniKaniTabViewController.swift, ios/ReviewSettingsViewController.swift, ios/Settings.swift
Issue #586 was opened as a "bug" because the review "batch size" property wasn't consistent with the lesson "batch size" property and as a result, created false expectations from users about what the app was supposed to do. Lesson batch size sets the number of items that appear in a lesson. Users expected review batch size to do the same thing for reviews, but in reality, controlled something else. #745 was implemented to alleviate the pain of this problem.
This PR implements a new feature that closes #586 because it provides the behavior that users were originally expecting from the review "batch size" property.
From my home screen you can see that I have 284 reviews to complete. This is existing behavior. No change
When I start doing reviews, I can see that the review queue at the top …
=> feat(reviews): batch size

ios/MainWaniKaniTabViewController.swift, ios/ReviewSession.swift
I accidentally introduced a small bug in #797 where the review order isn't getting respected.
The reason for this is because the review queue starts off random, and I truncated the review queue in `ios/MainWaniKaniTabViewController.swift`, which then gets passed to `ios/ReviewSession.swift` where sorting happens. So long story short, I was truncating the queue BEFORE it got sorted. I updated the code to truncate after sorting and now everything is working as expected.
=> fix(reviews): sort queue before truncating

ios/CommonErrors.swift, ios/LocalCachingClient.swift, ios/LoginViewController.swift, ios/MainViewController.swift, ios/Tsurukame.xcodeproj/project.pbxproj, ios/WaniKaniAPI/Sources/WaniKaniAPI/WebClient.swift
Currently, no error is shown when accounts are in hibernation. This PR shows errors on the main screen and on login (for both username/password and API token) when the account is in hibernation. I don't think we can handle this for the user, so this points the user to the WaniKani website to fix the problem.
Screen shown on website when in hibernation:
What the app shows (this is the login screen but same idea if already logged in):
Fixes #767
=> Fix: Show API errors when account in hibernation

ios/AnswerChecker.swift
First, thanks for the great app.
I just ran into a bug where, if you enter a kanji reading in the meaning field for a vocab item, the reading is marked as correct even though it was actually incorrect for the given item.
This PR fixes that issue by returning `AnswerCheckerResult.OtherKanjiReading` from `checkAnswer` if the user enters the kanji reading in this situation. This causes the screen to shake but doesn't mark the reading as correct.
Repro:
君 vocab item
Enter "kun" (correct reading is きみ)
Hit enter, screen shakes.
Enter "buddy" (correct meaning)
Answer is accepted.
Expected behavior:
君 vocab item
Enter "kun" (correct reading is きみ)
Hit enter, screen shakes.
Enter "buddy" (correct meaning)
User moves onto reading portion.
=> Don't mark the answer as correct if the user enters the kanji reading in the meaning field for a vocab item

ios/TKMKanaInput.m
When doing reviews, when you are typing at the end of the text field, all is well. However, if you make a mistake and go back to fix it, as soon as the text is transformed (say `ku` to `く`), the cursor auto-shifts to the end due to the text replacement in `TKMKanaInput`.
This PR fixes that by fixing the selection after the text has been changed.
Some GIFs for demonstration. (Not perfect GIF recordings, but they should give you the idea.)
Before:
After:
Fixes #743
=> Fix bug: Typing in not-latest position in TKMKanaInput moves caret to end

ios/Generated/IB-Segues+Generated.swift, ios/MainWaniKaniTabViewController.swift, ios/Resources/Main.storyboard, ios/ReviewItem.swift
These are items that have been guru'd but have fallen back to the apprentice SRS stage. Not exactly leeches (based on definitions on the forums such as https://community.wanikani.com/t/userscript-wanikani-open-framework-additional-filters-recent-lessons-leech-training-related-items-and-more/30512), but this will at least help some users that keep failing some items (namely, me, myself, and I).
The steps to make actual leech training available would touch a greater part of the codebase, as we'd have to update the API pulls to get review stats and then make use of that when filtering for leeches, along with at least one setting for the math formula for calculating what a leech is. This PR at least helps users who continuously guru -> apprentice -> guru -> apprentice items. (Yes, I'm guilty …
=> Allow user to practice apprentice leech items

ios/ReviewViewController.swift
After getting a shake and red letters, sometimes the full text would change red after making further changes despite changing the full text in TKMInput. Removing typing attributes fixes that. (The attributes were somehow carrying over into the full string when replacing text, likely because of where the user's cursor was, so removing those typing attributes removes the attributes moving into the full string.)
A reliable way to replicate is by going to a review for 分ける, typing `わけry`, hitting enter, erasing `y`, then typing. All text turns red.
Done in ReviewViewController since that's where the highlighting is done in the first place.
See also: https://stackoverflow.com/questions/34689141
Before:
After:
(P.S. Test builds are failing to publish right now; is there some new apple agreement …
=> Fix red text highlighting issue in reviews

ios/ReviewViewController.swift
#813 broke text alignment in certain cases. Sorry about that. Replicate by typing any hiragana or three, then select all, then type again -> alignment goes to left. (Why removing typing attributes breaks the center text alignment set on the overall field is unknown to me.)
This PR fixes it by making sure to retain the text alignment in the typing attributes, which retains the center alignment when typing.
=> Fix bug: Retain center text when replacing typing attributes

ios/TKMKanaInput+Internals.h, ios/TKMKanaInput.m
Makes it so that single char (e.g. `a` to `あ`) works properly when `range.length > 0` in `TKMInput`. Implemented this in its own `if` case just to keep things straightforward without potentially messing up some other parts of the text replacement code.
See #744 for wrong behavior and the following GIF for the new behavior:
Also fixes a code style issue where `[textField setTextAlignment:NSTextAlignmentCenter];` should be `textField.textAlignment = NSTextAlignmentCenter;`.
Closes #744
=> Fix TKMInput single char input with range.length>0

ios/ReviewSession.swift, ios/Settings.swift
Adds a new review order called "Alternating SRS stage", which alternates reviews with the lowest and highest SRS stages.
For example, if the user has reviews with SRS stages `[1, 2, 3, 4, 5, 6, 7]`, then this option will present these reviews in the order `[1, 7, 2, 6, 3, 5, 4]`.
I've also reordered the enum entries to place all of the "SRS stage" options together, which should be a slight improvement to the UI. Previously, "Descending SRS stage" was near the bottom of the list while "Ascending SRS stage" was near the top.
=> Add "Alternating SRS stage" review order

ios/MainWaniKaniTabViewController.swift, ios/ReviewSession.swift, ios/ReviewUtils.swift
see #823 for background. Sorting the review queue inside the review session component causes everything that uses the reviewSession component (lessons, burned items, leeches, etc) gets truncated when we really just want to truncate the review session only
instead of sorting inside the review session component, sort when initializing the component from the main component
this was caused by #801 
closes #823
=> fix(reviews): sort queue when building session

ios/ReviewSession.swift, ios/Settings.swift, ios/SubjectDetailsSettingsViewController.swift, ios/Tsurukame.xcodeproj/project.pbxproj
This pull pull request adds a new feature to settings / reviews that allows you to skip kanji readings in quizzes. **This impacts both reviews and lessons.**
I personally do not find a lot of value to learning the kanji readings through SRS because a given kanji can have lots of different readings depending on the word it's in.
One such instance for example is `日`, which has different readings in every single word below:
```
日本
七日
休日
日曜日
朝日
```
If you enable the `show all kanji readings` feature, Tsurukame will show you all readings for that kanji
However, Wanikani still only accepts `にち` as the "valid" reading for this kanji.
This is kind of an extreme example, since many kanjis really do only have one or two readings, but I have encountered several such examples in my studies to the …
=> allow skipping kanji readings

ios/MainWaniKaniTabViewController.swift
closes #827. see #827 for more info
TLDR the practice sessions are currently not being shuffled so when you do stuff like review burned items, you end up in the same order every single time. 
this PR shuffles practice sessions before initiating the review session so that you end up with fresh sessions each time
=> fix(practice): shuffle practice sessions

ios/ReviewSession.swift
Reverts a small change in #824 to make sure the active queue size in reviews is correct.
@zjgoodman Could you help me understand why the change in #824 to remove the use of `Settings.reviewBatchSize` was made? The active queue size shouldn't be controlled by the number of reviews, I believe. I did a test, and the limitation for review items still works with the active queue size being set to `Settings.reviewBatchSize`.
Closes #829
=> Re-integrate Settings.reviewBatchSize use

ios/ReviewQuickSettings/ReviewQuickSettingsAudioMenu.swift
I noticed a bug where toggling the "interrupt background audio" option does not work as expected. This PR fixes that issue
=> Fix bug with "Interrupt background audio"

ios/Generated/IB-Segues+Generated.swift, ios/LessonPickerViewController.swift, ios/LocalCachingClient.swift, ios/MainWaniKaniTabViewController.swift, ios/Resources/Main.storyboard, ios/ReviewSession.swift, ios/ReviewViewController.swift, ios/SubjectDetailsView.swift, ios/SubjectsExcluded.storyboard, ios/SubjectsExcludedViewController.swift, ios/Tsurukame.xcodeproj/project.pbxproj
this PR introduces a feature that allows users to **exclude** items that they don't care about, preventing them from appearing in their review queues
As I have progressed through wanikani, I have encountered various vocabulary words that I personally do not find value in studying, yet they appear in my review queue. they also contribute to my overall review count's number, which is currently quite high, which discourages me from doing reviews and also makes me feel like I'm not making much progress
A few examples of such words that I prefer not to study include:
```
金玉 testicles
ナポレオン3世 napoleon the 3rd
ハート形 heart shape
```
Additionally, there exists words that I do find value to learning, but there exist many duplicates of the words that are redundant and annoying to study. For example …
=> feat: exclude items

ios/LessonSettingsViewController.swift
Changed the minimum selectable lessons in the batch from 3 to 1 by adding explicit choices for "1 lesson" and "2 lessons". This allows users to pick smaller batch sizes, improving flexibility and enabling better control via user defaults.
- Added `vc.addChoice(name: "1 lesson", value: 1)`
- Updated range to start from 2 (`vc.addChoicesFromRange(2 ... 10, suffix: " lessons")`)
Previously, the minimum was 3 lessons, which limited user options. Now users can select 1 or 2 lessons, which can help with skipping the lesson picker.
=> Adds options for lessonBatchSize to range from 1-10 

ios/LessonSettingsViewController.swift, ios/LocalCachingClient.swift, ios/MainWaniKaniTabViewController.swift, ios/ReviewViewController.swift, ios/Settings.swift, ios/SubjectDetailsView.swift
See #836. Some users may not want this feature and/or may want the options to not be so prominent above part of speech/other information when the majority of the time things will remain enabled.
This PR does two things:
* Allows disabling of the exclude items feature in its entirety (keeps any previously-excluded data but pretends like it was never excluded)
* Moves options for excluding items to the bottom of the subject details
CC @zjgoodman
=> Tweak: exclude items feature
