davidsansome/tsurukame

- ios/SubjectDetailsView.m
- ios/Tables/TKMMarkupModelItem.h
- ios/Tables/TKMMarkupModelItem.m
This pull request closes issue #67.
Hope you like it :)
> Fix text color of marked words in hints

- .gitignore
- ios/ReviewViewController.mm
Partially addresses #31 by making the question font size bigger on iPads.
> Boost iPad question font size

- ios/LocalCachingClient.mm
I think this is the solution for eternally queued updates I was seeing, that I mentioned in #122. 
It turns out it's possible to start reviews before the app has caught up with reviews that you did on another device, especially if the other device didn't finish reporting reviews before it suspended. In that case, one of the devices ends up with progress waiting to report that can't ever be accepted, because the server rejects the request with 422 Unprocessable Entity.
Since the server is telling is that there is no point in the future where this particular progress report will _ever_ be accepted, I'm using that as my queue to simply delete that progress from the database and call it good. Plus, installing this commit fixed all my stuck queued progress. :)
> Discard explicitly rejected progress

- ios/TKMAudio.m
it turns out this KeyValueObserver was firing allll the time, including
every single time the app ever activated. we don't actually want to set
the state machine into "audio is playing now" just because you left the
app and came back while there was an audio file loaded up and able to be
played.
fixes #130
> only set TKMAudioPlaying once, before playing

- ios/Info.plist
- ios/Tsurukame.entitlements
- ios/Tsurukame.xcodeproj/project.pbxproj
> Add macOS support by checking macOS checkbox

- ios/Main.storyboard
- ios/ReviewViewController.swift
- ios/Settings.h
- ios/Settings.m
- ios/SettingsViewController.m
I have been using Tsurukame for a bit now and it's great. One thing I was missing was the [Wanikani Review SRS/Level Indicator](https://greasyfork.org/en/scripts/15582-wanikani-review-srs-level-indicator) user script. It's not a major thing to be lacking but I had some time this week so I added it in my own fork. Here is the diff if you would like to include it for others in the future (controlled via settings, off by default).
> Wanikani Review SRS/Level Indicator

- ios/FontSizeViewController.h
- ios/FontSizeViewController.m
- ios/Resources/Main.storyboard
- ios/ReviewViewController.swift
- ios/Settings.h
- ios/Settings.m
- ios/SettingsViewController.m
- ios/Tsurukame.xcodeproj/project.pbxproj
Just a humble contribution to this awesome app. I use Tsurukame all the time and it's amazing. Thank you very much!
> Simple font size selector for reviews

- ios/CurrentLevelChartController.m
- ios/Info.plist
- ios/LoginViewController.m
- ios/MainViewController.m
- ios/ReviewViewController.swift
- ios/SettingsViewController.m
- ios/SubjectDetailsView.swift
- ios/TKMFontsViewController.m
- ios/TKMOfflineAudioViewController.mm
- ios/TKMReviewMenuViewController.m
- ios/Tables/TKMDownloadModelItem.m
- ios/Tables/TKMMarkupModelItem.m
- ios/VocabularyHighlighter.swift
There's probably still more that needs to be done, but this at least makes all the text readable in dark mode.
> Dark mode support

- ios/Resources/Main.storyboard
- ios/ReviewViewController.swift
- ios/Settings.h
- ios/SettingsViewController.m
Should fix #173 - attempted to add newest & oldest available sort.
> Added newest & oldest available sort (Fixes #173)

- ios/AnswerChecker.swift
To fix #187 and #213, this code attempts to narrow the valid character range.
> Narrow accepted character range (Fixes #187 and #213)

- README.md
> Update README to address CocoaPods & signing (Fixes #249)

- ios/CurrentLevelReviewTimeItem.swift
- ios/MainViewController.m
- ios/Tsurukame.xcodeproj/project.pbxproj
In order to fix #20, this commit shows the next current level review.
> Show next current level review (Fixes #20)

- ios/LessonsViewController.m
- ios/SuccessAnimation.m
- ios/TKMReviewContainerViewController.m
Fix #255 by removing the Apprentice level-up popup.
> Remove Apprentice level-up popup (Fixes #255)

- ios/SubjectDetailsView.swift
This PR starts adding #27 by showing existing notes.
> For now, it would be great to be at least able to read them.
> Render subject notes

- ios/Resources/Main.storyboard
- ios/ReviewViewController.swift
- ios/Settings.h
- ios/SettingsViewController.m
Fix #281 by adding descending SRS order
> Add descending SRS order (Fixes #281)

- ios/proto/Wanikani+Convenience.m
Fix #237 by only returning passed at date if the subject is at least Guru.
> Only return passed at date if at least Guru (Fixes #237)

- ios/TKMOfflineAudioViewController.mm
Fixes audio download text, replacing phone with actual device. Also assists #286
> Correct audio download text

- ios/ReviewViewController.swift
These changes allow users of hardware keyboards to have continual control of the UI during wrong answers with keyboard commands. This includes the following conditions listed below.
1. Keep the cursor in the text field on AnswerCheckerResult case OtherKanjiReading or ContainsInvalidCharacters, allowing the text to be edited after a shake animation.
2. When an answer is Incorrect, and before display of subject details, allow the backspace, keyboard enter, or numeric keypad enter key to clear the field and allow another entry.
3. When the subject details view is displayed, allow an enter key press to close the view and proceed to a new answer entry.
See #286 for a previous report of (1).
> Allow hardware keyboard control during wrong answers

- ios/LessonsViewController.swift
- ios/ReviewViewController.swift
Fixes #428 by adding new keyboard navigation to match website better
> Add additional hotkeys to correspond with WK site

- ios/ApprenticeLimitViewController.swift
- ios/LocalCachingClient.swift
- ios/MainViewController.swift
- ios/Resources/Settings.storyboard
- ios/Settings.swift
- ios/SettingsViewController.swift
- ios/Tsurukame.xcodeproj/project.pbxproj
Fixes #363 by implementing the changes requested in order to fix #441 (the previous PR)
> Introduce apprentice limit to disable lessons, with requested changes

- ios/Resources/Settings.storyboard
- ios/ReviewViewController.swift
- ios/Settings.swift
- ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
Fixes #355 by adding longest relative wait order.
> Longest relative wait (Fixes #355)

- ios/ReviewViewController.swift
- ios/Settings.swift
- ios/SettingsViewController.swift
Fixes #48 by adding partially correct answer pausing
> Pause on partially correct answers (Fixes #48)

- ios/SubjectDetailsView.swift
Fixes #27 and closes #361 by adding edit meaning/reading notes buttons.
> Edit notes (Fixes #27, #361)

- ios/ReviewViewController.swift
- ios/Settings.swift
- ios/SettingsViewController.swift
Fixes #347 by implementing Anki mode
> Anki mode (Fixes #347)

- ios/ReviewViewController.swift
Relevant Issue: https://github.com/davidsansome/tsurukame/issues/595
If the user taps the screen too fast after a correct submission, the just submitted **correct** answer will be marked **incorrect**, and this apparently gets rejected by Wanikani. I came a across this issue this week after I started using Anki mode, and got more than 200 reviews back when I forced a full sync, after suspecting something was off with Tsurukame's synchronization.
- fixed: Anki Mode tagging correct answers as incorrect when users tapped to show the next review element while the SubjectDetailsView was animating
- added: when users tap the canvas after clicking on a button (correct, incorrect, etc), but before the animation is done, the action gets cached, so the submit button will be automatically be …
> [Bugfix | Anki Mode] 595 - Sync Issues Causing Lost Progress

- ios/LocalCachingClient.swift
- ios/MainViewController.swift
- ios/Resources/Main.storyboard
- ios/Resources/Subjects.storyboard
- ios/SRSStageCategoryItem.swift
- ios/SubjectsByCategoryViewController.swift
- ios/Tsurukame.xcodeproj/project.pbxproj
- ios/WaniKaniAPI/Sources/WaniKaniAPI/ProtobufExtensions.swift
You now have the ability to view all apprentice/guru/etc. items at once. Useful especially for burned items.
> Add ability to view list of items by SRS category

- ios/Audio.swift
- ios/SubjectDetailsView.swift
- ios/Tables/ArtworkManager.swift
- ios/Tables/ArtworkModelItem.swift
Fix [PR - "Add ArtWork by @AmandaBear to Subject #653"](https://github.com/davidsansome/tsurukame/pull/653/files) 
@davidsansome
> Fix network issue and screen size issue for "Add Artwork by @AmandaBear to Subject #653"

- ios/LocalCachingClient.swift
In the current version of the app, because recent mistakes are stored in the local db, performing a full refresh from the WK server causes those mistakes to be lost, which can be very annoying if you do this accidentally.
This PR fixes that by:
1. Before refresh, load recent mistakes in last 24 hrs from local db.
2. After refresh and db updated, re-insert the recent mistake data into the local db.
NOTE: This does rely on subject IDs remaining the same before/after refresh. If only this data was easily available through the API 😞 Ideally these sorts of things this app stores would get synced to iCloud and thus show up on both macOS and iOS if you were using both devices or something, I suppose...
> Remember recent mistakes after full refresh

- ios/Audio.swift
- ios/ReviewMenuViewController.swift
- ios/ReviewSettingsViewController.swift
- ios/Settings.swift
@davidsansome Long time fan of Tsurukame. 
I often have music or something playing in my headphones and feel reluctant to jump in for a quick review because I know that every time audio plays it will harshly interrupt. I saw that someone else had the same request in #625 so added a setting to allow the option. 
Sorry to just barge in with a PR, not sure the etiquette for contributing on this project.
> Issue 625 Allow background audio

- ios/UpcomingReviewsViewController.swift
A simple PR. It bugged me that I couldn't do the whole swipe back to go backward in the upcoming reviews screen. This PR allows that to happen.
> Allow swiping backward in upcoming reviews screen
